name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت پروژه
        uses: actions/checkout@v4

      - name: تنظیم Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: نصب Android SDK
        uses: android-actions/setup-android@v3

      - name: نصب Android SDK Platform
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: نصب Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: ساخت APK
        run: gradle -p android-app assembleDebug

      - name: ذخیره APK
        uses: actions/upload-artifact@v4
        with:
          name: Estekhdam-Persenel-APK
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
